name:                brainfxck-dsl
version:             0.1.0.0
github:              "4afS/brainfxck-dsl"
license:             BSD3
author:              "4afS"
maintainer:          "4afs.h1@gmail.com"
copyright:           "2019 4afS"

extra-source-files:
- README.md
- ChangeLog.md

category:            DSL
description:         Please see the README on GitHub at <https://github.com/4afS/brainfxck-dsl#readme>

dependencies:
- base >= 4.7 && < 5
- free
- mtl
- lens
- vector

library:
  source-dirs: src

executables:
  brainfxck-dsl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfxck-dsl

tests:
  brainfxck-dsl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfxck-dsl
    - hspec
